apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.5.17
        args:
        - --source=ingress
        - --domain-filter=seriousben.com
        - --provider=google
        - --google-project=projects-seriousben
        - --registry=txt
        - --txt-owner-id=seriousben
        #- --dry-run